#server:
#  port: 8082
#spring:
#  main:
#    banner-mode: off

#spring:
#  profiles:
#    active: prod

book:
  author: wangyunfei
  name: spring boot

author:
  name: wangyunfei
  age: 32

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdemo_db
    username: root
    password:
#  jackson:
#      time-zone: GMT+8,
#      date-format: yyyy-MM-dd HH:mm:ss
